name: Deploy
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    name: Deploy proxy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to fetch tags and commit history

      - name: Calculate Version and Date
        run: |
          echo "APP_VERSION=$(git describe --tags || git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "APP_LASTMOD=$(git log -1 --format=%cd --date=format:'%m/%d/%Y')" >> $GITHUB_ENV

      - name: Deploy to Fly.io
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: >
          flyctl deploy --remote-only
          --build-arg APP_VERSION="${{ env.APP_VERSION }}" 
          --build-arg APP_LASTMOD="${{ env.APP_LASTMOD }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Purge Cloudflare Cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE }}/purge_cache" \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{"purge_everything":true}'